AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG16 model
BATCH_SIZE: 32
INCLUDE_TOP: False
WEIGHTS: imagenet
EPOCHS_PHASE_1: 1
EPOCHS_PHASE_2: 1
CLASSES: 4
LEARNING_RATE_PHASE_1: 0.01
LEARNING_RATE_PHASE_2: 0.001
FREEZE_N: 4
FREEZE_ALL: True
DO_OFFLINE_AUGM: True
TARGET_SIZE_AUGM: 250
CALLBACKS:
  REDUCE_LR:
    FACTOR: 0.8
    PATIENCE: 7